networks:
  dev:

services:
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "80:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - dev

  frontend:
    build:
      context: .
    networks:
      - dev